using ModComponent.Behaviours;
using ModComponent.Blueprints;
using ModComponent.Components;
using ModComponent.Utilities;
using System;
using System.Linq;

namespace ModComponent.SDK
{
    internal class DataSerializer
    {
        internal static object SerializeBlueprint(object blueprint)
        {
            return blueprint switch
            {
                ModRecipe modRecipe => new
                {
                    modRecipe.RecipeName,
                    modRecipe.RecipeDescription,
                    RecipeIcon = modRecipe.RecipeIcon != null ? modRecipe.RecipeIcon.Icon.name : null ?? "",
                    modRecipe.RequiredSkillLevel,
                    AllowedCookingPots = modRecipe.AllowedCookingPots?.Select(pot => pot.name).ToArray() ?? new string[0],
                    BlueprintData = new
                    {
                        modRecipe.Name,
                        RequiredGear = modRecipe.RequiredGear?.Select(g => new { Item = g.GearItem.name, g.Count, Units = Enum.GetName(typeof(UnitsType), g.Units) }).ToArray(),
                        RequiredPowder = modRecipe.RequiredPowder?.Select(g => new { Powder = g.PowderItem.name, g.QuantityInKilograms }).ToArray(),
                        RequiredLiquid = modRecipe.RequiredLiquid?.Select(g => new { Liquid = g.LiquidItem.name, g.VolumeInLitres }).ToArray(),
                        CraftedResult = modRecipe.CraftedResult != null ? modRecipe.CraftedResult.name : null ?? "",
                        modRecipe.CraftedResultCount,
                        modRecipe.DurationMinutes,
                        CraftingAudio = modRecipe.CraftingAudio != null ? modRecipe.CraftingAudio.name : null ?? ""
                    }
                },
                ModBlueprint modBlueprint => new
                {
                    modBlueprint.Name,
                    RequiredGear = modBlueprint.RequiredGear?.Select(g => new { Item = g.GearItem.name, g.Count, Units = Enum.GetName(typeof(UnitsType), g.Units )}).ToArray(),
                    RequiredPowder = modBlueprint.RequiredPowder?.Select(g => new { Powder = g.PowderItem.name, g.QuantityInKilograms }).ToArray(),
                    RequiredLiquid = modBlueprint.RequiredLiquid?.Select(g => new { Liquid = g.LiquidItem.name, g.VolumeInLitres }).ToArray(),
                    RequiredTool = modBlueprint.RequiredTool != null ? modBlueprint.RequiredTool.name : null ?? "",
                    OptionalTools = modBlueprint.OptionalTools?.Select(tool => tool.name).ToArray(),
                    RequiredCraftingLocation = modBlueprint.RequiredCraftingLocation.ToString(),
                    modBlueprint.RequiresLitFire,
                    modBlueprint.RequiresLight,
                    CraftedResult = modBlueprint.CraftedResult != null ? modBlueprint.CraftedResult.name : null ?? "",
                    modBlueprint.CraftedResultCount,
                    modBlueprint.DurationMinutes,
                    CraftingAudio = modBlueprint.CraftingAudio != null ? modBlueprint.CraftingAudio.name : null ?? "",
                    AppliedSkill = modBlueprint.AppliedSkill.ToString(),
                    ImprovedSkill = modBlueprint.ImprovedSkill.ToString()
                },
                _ => blueprint
            };
        }

        internal static object SerializeComponent(object component)
        {
            return component switch
            {
                ModAmmoComponent modAmmoComponent => new
                {
                    modAmmoComponent.DisplayNameLocalizationId,
                    modAmmoComponent.DescriptionLocalizatonId,
                    modAmmoComponent.InventoryActionLocalizationId,
                    modAmmoComponent.WeightKG,
                    modAmmoComponent.DaysToDecay,
                    modAmmoComponent.MaxHP,
                    InitialCondition = modAmmoComponent.InitialCondition.ToString(),
                    InventoryCategory = modAmmoComponent.InventoryCategory.ToString(),
                    PickUpAudio = modAmmoComponent.PickUpAudio != null ? modAmmoComponent.PickUpAudio.name : "",
                    PutBackAudio = modAmmoComponent.PutBackAudio != null ? modAmmoComponent.PutBackAudio.name : "",
                    StowAudio = modAmmoComponent.StowAudio != null ? modAmmoComponent.StowAudio.name : "",
                    WornOutAudio = modAmmoComponent.WornOutAudio != null ? modAmmoComponent.WornOutAudio.name : "",
                    modAmmoComponent.InspectOnPickup,
                    modAmmoComponent.InspectDistance,
                    InspectAngles = new float[] { modAmmoComponent.InspectAngles.x, modAmmoComponent.InspectAngles.y, modAmmoComponent.InspectAngles.z },
                    InspectOffset = new float[] { modAmmoComponent.InspectOffset.x, modAmmoComponent.InspectOffset.y, modAmmoComponent.InspectOffset.z },
                    InspectScale = new float[] { modAmmoComponent.InspectScale.x, modAmmoComponent.InspectScale.y, modAmmoComponent.InspectScale.z },
                    NormalModel = modAmmoComponent.NormalModel != null ? modAmmoComponent.NormalModel.name : "",
                    InspectModel = modAmmoComponent.InspectModel != null ? modAmmoComponent.InspectModel.name : "",

                    AmmoForGunType = modAmmoComponent.AmmoForGunType.ToString()
                },
                ModBedComponent modBedComponent => new
                {
                    modBedComponent.DisplayNameLocalizationId,
                    modBedComponent.DescriptionLocalizatonId,
                    modBedComponent.InventoryActionLocalizationId,
                    modBedComponent.WeightKG,
                    modBedComponent.DaysToDecay,
                    modBedComponent.MaxHP,
                    InitialCondition = modBedComponent.InitialCondition.ToString(),
                    InventoryCategory = modBedComponent.InventoryCategory.ToString(),
                    PickUpAudio = modBedComponent.PickUpAudio != null ? modBedComponent.PickUpAudio.name : "",
                    PutBackAudio = modBedComponent.PutBackAudio != null ? modBedComponent.PutBackAudio.name : "",
                    StowAudio = modBedComponent.StowAudio != null ? modBedComponent.StowAudio.name : "",
                    WornOutAudio = modBedComponent.WornOutAudio != null ? modBedComponent.WornOutAudio.name : "",
                    modBedComponent.InspectOnPickup,
                    modBedComponent.InspectDistance,
                    InspectAngles = new float[] { modBedComponent.InspectAngles.x, modBedComponent.InspectAngles.y, modBedComponent.InspectAngles.z },
                    InspectOffset = new float[] { modBedComponent.InspectOffset.x, modBedComponent.InspectOffset.y, modBedComponent.InspectOffset.z },
                    InspectScale = new float[] { modBedComponent.InspectScale.x, modBedComponent.InspectScale.y, modBedComponent.InspectScale.z },
                    NormalModel = modBedComponent.NormalModel != null ? modBedComponent.NormalModel.name : "",
                    InspectModel = modBedComponent.InspectModel != null ? modBedComponent.InspectModel.name : "",

                    modBedComponent.ConditionGainPerHour,
                    modBedComponent.AdditionalConditionGainPerHour,
                    modBedComponent.WarmthBonusCelsius,
                    modBedComponent.DegradePerHour,
                    modBedComponent.BearAttackModifier,
                    modBedComponent.WolfAttackModifier,
                    OpenAudio = modBedComponent.OpenAudio != null ? modBedComponent.OpenAudio.name : null ?? "",
                    CloseAudio = modBedComponent.CloseAudio != null ? modBedComponent.CloseAudio.name : null ?? "",
                    PackedMesh = modBedComponent.PackedMesh != null ? modBedComponent.NormalModel.name : "",
                    UsableMesh = modBedComponent.UsableMesh != null ? modBedComponent.NormalModel.name : "",
                },
                ModBodyHarvestComponent modBodyHarvestComponent => new
                {
                    modBodyHarvestComponent.DisplayNameLocalizationId,
                    modBodyHarvestComponent.DescriptionLocalizatonId,
                    modBodyHarvestComponent.InventoryActionLocalizationId,
                    modBodyHarvestComponent.WeightKG,
                    modBodyHarvestComponent.DaysToDecay,
                    modBodyHarvestComponent.MaxHP,
                    InitialCondition = modBodyHarvestComponent.InitialCondition.ToString(),
                    InventoryCategory = modBodyHarvestComponent.InventoryCategory.ToString(),
                    PickUpAudio = modBodyHarvestComponent.PickUpAudio != null ? modBodyHarvestComponent.PickUpAudio.name : "",
                    PutBackAudio = modBodyHarvestComponent.PutBackAudio != null ? modBodyHarvestComponent.PutBackAudio.name : "",
                    StowAudio = modBodyHarvestComponent.StowAudio != null ? modBodyHarvestComponent.StowAudio.name : "",
                    WornOutAudio = modBodyHarvestComponent.WornOutAudio != null ? modBodyHarvestComponent.WornOutAudio.name : "",
                    modBodyHarvestComponent.InspectOnPickup,
                    modBodyHarvestComponent.InspectDistance,
                    InspectAngles = new float[] { modBodyHarvestComponent.InspectAngles.x, modBodyHarvestComponent.InspectAngles.y, modBodyHarvestComponent.InspectAngles.z },
                    InspectOffset = new float[] { modBodyHarvestComponent.InspectOffset.x, modBodyHarvestComponent.InspectOffset.y, modBodyHarvestComponent.InspectOffset.z },
                    InspectScale = new float[] { modBodyHarvestComponent.InspectScale.x, modBodyHarvestComponent.InspectScale.y, modBodyHarvestComponent.InspectScale.z },
                    NormalModel = modBodyHarvestComponent.NormalModel != null ? modBodyHarvestComponent.NormalModel.name : "",
                    InspectModel = modBodyHarvestComponent.InspectModel != null ? modBodyHarvestComponent.InspectModel.name : "",

                    modBodyHarvestComponent.CanCarry,
                    HarvestAudio = modBodyHarvestComponent.HarvestAudio != null ? modBodyHarvestComponent.HarvestAudio.name : null ?? "",
                    GutPrefab = modBodyHarvestComponent.GutPrefab != null ? modBodyHarvestComponent.GutPrefab.name : null ?? "",
                    modBodyHarvestComponent.GutQuantity,
                    modBodyHarvestComponent.GutWeightKgPerUnit,
                    HidePrefab = modBodyHarvestComponent.HidePrefab != null ? modBodyHarvestComponent.HidePrefab.name : null ?? "",
                    modBodyHarvestComponent.HideQuantity,
                    modBodyHarvestComponent.HideWeightKgPerUnit,
                    MeatPrefab = modBodyHarvestComponent.MeatPrefab != null ? modBodyHarvestComponent.MeatPrefab.name : null ?? "",
                    modBodyHarvestComponent.MeatAvailableMinKG,
                    modBodyHarvestComponent.MeatAvailableMaxKG
                },
                ModCharcoalComponent modCharcoalComponent => new
                {
                    modCharcoalComponent.DisplayNameLocalizationId,
                    modCharcoalComponent.DescriptionLocalizatonId,
                    modCharcoalComponent.InventoryActionLocalizationId,
                    modCharcoalComponent.WeightKG,
                    modCharcoalComponent.DaysToDecay,
                    modCharcoalComponent.MaxHP,
                    InitialCondition = modCharcoalComponent.InitialCondition.ToString(),
                    InventoryCategory = modCharcoalComponent.InventoryCategory.ToString(),
                    PickUpAudio = modCharcoalComponent.PickUpAudio != null ? modCharcoalComponent.PickUpAudio.name : "",
                    PutBackAudio = modCharcoalComponent.PutBackAudio != null ? modCharcoalComponent.PutBackAudio.name : "",
                    StowAudio = modCharcoalComponent.StowAudio != null ? modCharcoalComponent.StowAudio.name : "",
                    WornOutAudio = modCharcoalComponent.WornOutAudio != null ? modCharcoalComponent.WornOutAudio.name : "",
                    modCharcoalComponent.InspectOnPickup,
                    modCharcoalComponent.InspectDistance,
                    InspectAngles = new float[] { modCharcoalComponent.InspectAngles.x, modCharcoalComponent.InspectAngles.y, modCharcoalComponent.InspectAngles.z },
                    InspectOffset = new float[] { modCharcoalComponent.InspectOffset.x, modCharcoalComponent.InspectOffset.y, modCharcoalComponent.InspectOffset.z },
                    InspectScale = new float[] { modCharcoalComponent.InspectScale.x, modCharcoalComponent.InspectScale.y, modCharcoalComponent.InspectScale.z },
                    NormalModel = modCharcoalComponent.NormalModel != null ? modCharcoalComponent.NormalModel.name : "",
                    InspectModel = modCharcoalComponent.InspectModel != null ? modCharcoalComponent.InspectModel.name : "",

                    modCharcoalComponent.SurveyGameMinutes,
                    modCharcoalComponent.SurveyRealSeconds,
                    modCharcoalComponent.SurveySkillExtendedHours,
                    SurveyLoopAudio = modCharcoalComponent.SurveyLoopAudio != null ? modCharcoalComponent.SurveyLoopAudio.name : null ?? ""
                },
                ModClothingComponent modClothingComponent => new
                {
                    modClothingComponent.DisplayNameLocalizationId,
                    modClothingComponent.DescriptionLocalizatonId,
                    modClothingComponent.InventoryActionLocalizationId,
                    modClothingComponent.WeightKG,
                    modClothingComponent.DaysToDecay,
                    modClothingComponent.MaxHP,
                    InitialCondition = modClothingComponent.InitialCondition.ToString(),
                    InventoryCategory = modClothingComponent.InventoryCategory.ToString(),
                    PickUpAudio = modClothingComponent.PickUpAudio != null ? modClothingComponent.PickUpAudio.name : "",
                    PutBackAudio = modClothingComponent.PutBackAudio != null ? modClothingComponent.PutBackAudio.name : "",
                    StowAudio = modClothingComponent.StowAudio != null ? modClothingComponent.StowAudio.name : "",
                    WornOutAudio = modClothingComponent.WornOutAudio != null ? modClothingComponent.WornOutAudio.name : "",
                    modClothingComponent.InspectOnPickup,
                    modClothingComponent.InspectDistance,
                    InspectAngles = new float[] { modClothingComponent.InspectAngles.x, modClothingComponent.InspectAngles.y, modClothingComponent.InspectAngles.z },
                    InspectOffset = new float[] { modClothingComponent.InspectOffset.x, modClothingComponent.InspectOffset.y, modClothingComponent.InspectOffset.z },
                    InspectScale = new float[] { modClothingComponent.InspectScale.x, modClothingComponent.InspectScale.y, modClothingComponent.InspectScale.z },
                    NormalModel = modClothingComponent.NormalModel != null ? modClothingComponent.NormalModel.name : "",
                    InspectModel = modClothingComponent.InspectModel != null ? modClothingComponent.InspectModel.name : "",

                    Region = modClothingComponent.Region.ToString(),
                    MinLayer = modClothingComponent.MinLayer.ToString(),
                    MaxLayer = modClothingComponent.MaxLayer.ToString(),
                    MovementSound = modClothingComponent.MovementSound.ToString(),
                    Footwear = modClothingComponent.Footwear.ToString(),
                    modClothingComponent.DaysToDecayWornOutside,
                    modClothingComponent.DaysToDecayWornInside,
                    modClothingComponent.Warmth,
                    modClothingComponent.WarmthWhenWet,
                    modClothingComponent.Windproof,
                    modClothingComponent.Waterproofness,
                    modClothingComponent.Toughness,
                    modClothingComponent.SprintBarReduction,
                    modClothingComponent.DecreaseAttackChance,
                    modClothingComponent.IncreaseFleeChance,
                    modClothingComponent.HoursToDryNearFire,
                    modClothingComponent.HoursToDryWithoutFire,
                    modClothingComponent.HoursToFreeze,
                    MainTexture = modClothingComponent.MainTexture != null ? modClothingComponent.MainTexture.name : "",
                    BlendTexture = modClothingComponent.BlendTexture != null ? modClothingComponent.BlendTexture.name : "",
                    modClothingComponent.DrawLayer,
                    modClothingComponent.ImplementationType
                },
                ModCollectibleComponent modCollectibleComponent => new
                {
                    modCollectibleComponent.DisplayNameLocalizationId,
                    modCollectibleComponent.DescriptionLocalizatonId,
                    modCollectibleComponent.InventoryActionLocalizationId,
                    modCollectibleComponent.WeightKG,
                    modCollectibleComponent.DaysToDecay,
                    modCollectibleComponent.MaxHP,
                    InitialCondition = modCollectibleComponent.InitialCondition.ToString(),
                    InventoryCategory = modCollectibleComponent.InventoryCategory.ToString(),
                    PickUpAudio = modCollectibleComponent.PickUpAudio != null ? modCollectibleComponent.PickUpAudio.name : "",
                    PutBackAudio = modCollectibleComponent.PutBackAudio != null ? modCollectibleComponent.PutBackAudio.name : "",
                    StowAudio = modCollectibleComponent.StowAudio != null ? modCollectibleComponent.StowAudio.name : "",
                    WornOutAudio = modCollectibleComponent.WornOutAudio != null ? modCollectibleComponent.WornOutAudio.name : "",
                    modCollectibleComponent.InspectOnPickup,
                    modCollectibleComponent.InspectDistance,
                    InspectAngles = new float[] { modCollectibleComponent.InspectAngles.x, modCollectibleComponent.InspectAngles.y, modCollectibleComponent.InspectAngles.z },
                    InspectOffset = new float[] { modCollectibleComponent.InspectOffset.x, modCollectibleComponent.InspectOffset.y, modCollectibleComponent.InspectOffset.z },
                    InspectScale = new float[] { modCollectibleComponent.InspectScale.x, modCollectibleComponent.InspectScale.y, modCollectibleComponent.InspectScale.z },
                    NormalModel = modCollectibleComponent.NormalModel != null ? modCollectibleComponent.NormalModel.name : "",
                    InspectModel = modCollectibleComponent.InspectModel != null ? modCollectibleComponent.InspectModel.name : "",

                    modCollectibleComponent.HudMessageLocalizationId,
                    modCollectibleComponent.NarrativeTextLocalizationId,
                    TextAlignment = modCollectibleComponent.TextAlignment.ToString(),
                },
                ModFoodComponent modFoodComponent => new
                {
                    modFoodComponent.DisplayNameLocalizationId,
                    modFoodComponent.DescriptionLocalizatonId,
                    modFoodComponent.InventoryActionLocalizationId,
                    modFoodComponent.WeightKG,
                    modFoodComponent.DaysToDecay,
                    modFoodComponent.MaxHP,
                    InitialCondition = modFoodComponent.InitialCondition.ToString(),
                    InventoryCategory = modFoodComponent.InventoryCategory.ToString(),
                    PickUpAudio = modFoodComponent.PickUpAudio != null ? modFoodComponent.PickUpAudio.name : "",
                    PutBackAudio = modFoodComponent.PutBackAudio != null ? modFoodComponent.PutBackAudio.name : "",
                    StowAudio = modFoodComponent.StowAudio != null ? modFoodComponent.StowAudio.name : "",
                    WornOutAudio = modFoodComponent.WornOutAudio != null ? modFoodComponent.WornOutAudio.name : "",
                    modFoodComponent.InspectOnPickup,
                    modFoodComponent.InspectDistance,
                    InspectAngles = new float[] { modFoodComponent.InspectAngles.x, modFoodComponent.InspectAngles.y, modFoodComponent.InspectAngles.z },
                    InspectOffset = new float[] { modFoodComponent.InspectOffset.x, modFoodComponent.InspectOffset.y, modFoodComponent.InspectOffset.z },
                    InspectScale = new float[] { modFoodComponent.InspectScale.x, modFoodComponent.InspectScale.y, modFoodComponent.InspectScale.z },
                    NormalModel = modFoodComponent.NormalModel != null ? modFoodComponent.NormalModel.name : "",
                    InspectModel = modFoodComponent.InspectModel != null ? modFoodComponent.InspectModel.name : "",

                    modFoodComponent.Cooking,
                    modFoodComponent.CookingMinutes,
                    modFoodComponent.CookingUnitsRequired,
                    modFoodComponent.CookingWaterRequired,
                    modFoodComponent.CookingResult,
                    modFoodComponent.BurntMinutes,
                    Type = modFoodComponent.Type.ToString(),
                    modFoodComponent.CookingAudio,
                    modFoodComponent.StartCookingAudio,

                    modFoodComponent.DaysToDecayOutdoors,
                    modFoodComponent.DaysToDecayIndoors,
                    modFoodComponent.Calories,
                    modFoodComponent.Servings,
                    modFoodComponent.EatingTime,
                    EatingAudio = modFoodComponent.EatingAudio != null ? modFoodComponent.EatingAudio.name : null ?? "",
                    EatingPackagedAudio = modFoodComponent.EatingPackagedAudio != null ? modFoodComponent.EatingPackagedAudio.name : null ?? "",
                    modFoodComponent.ThirstEffect,
                    modFoodComponent.FoodPoisoning,
                    modFoodComponent.FoodPoisoningLowCondition,
                    modFoodComponent.ParasiteRiskIncrements,
                    modFoodComponent.Natural,
                    modFoodComponent.Raw,
                    modFoodComponent.Drink,
                    modFoodComponent.Meat,
                    modFoodComponent.Fish,
                    modFoodComponent.Canned,
                    modFoodComponent.Opening,
                    modFoodComponent.OpeningWithCanOpener,
                    modFoodComponent.OpeningWithKnife,
                    modFoodComponent.OpeningWithHatchet,
                    modFoodComponent.OpeningWithSmashing,
                    modFoodComponent.AffectCondition,
                    modFoodComponent.ConditionRestBonus,
                    modFoodComponent.ConditionRestMinutes,
                    modFoodComponent.AffectRest,
                    modFoodComponent.InstantRestChange,
                    modFoodComponent.RestFactorMinutes,
                    modFoodComponent.AffectCold,
                    modFoodComponent.InstantColdChange,
                    modFoodComponent.ColdFactorMinutes,
                    modFoodComponent.ContainsAlcohol,
                    modFoodComponent.AlcoholPercentage,
                    modFoodComponent.AlcoholUptakeMinutes,
                    modFoodComponent.VitaminC
                },
                ModCookableComponent modCookableComponent => new
                {
                    modCookableComponent.DisplayNameLocalizationId,
                    modCookableComponent.DescriptionLocalizatonId,
                    modCookableComponent.InventoryActionLocalizationId,
                    modCookableComponent.WeightKG,
                    modCookableComponent.DaysToDecay,
                    modCookableComponent.MaxHP,
                    InitialCondition = modCookableComponent.InitialCondition.ToString(),
                    InventoryCategory = modCookableComponent.InventoryCategory.ToString(),
                    PickUpAudio = modCookableComponent.PickUpAudio != null ? modCookableComponent.PickUpAudio.name : "",
                    PutBackAudio = modCookableComponent.PutBackAudio != null ? modCookableComponent.PutBackAudio.name : "",
                    StowAudio = modCookableComponent.StowAudio != null ? modCookableComponent.StowAudio.name : "",
                    WornOutAudio = modCookableComponent.WornOutAudio != null ? modCookableComponent.WornOutAudio.name : "",
                    modCookableComponent.InspectOnPickup,
                    modCookableComponent.InspectDistance,
                    InspectAngles = new float[] { modCookableComponent.InspectAngles.x, modCookableComponent.InspectAngles.y, modCookableComponent.InspectAngles.z },
                    InspectOffset = new float[] { modCookableComponent.InspectOffset.x, modCookableComponent.InspectOffset.y, modCookableComponent.InspectOffset.z },
                    InspectScale = new float[] { modCookableComponent.InspectScale.x, modCookableComponent.InspectScale.y, modCookableComponent.InspectScale.z },
                    NormalModel = modCookableComponent.NormalModel != null ? modCookableComponent.NormalModel.name : "",
                    InspectModel = modCookableComponent.InspectModel != null ? modCookableComponent.InspectModel.name : "",

                    modCookableComponent.Cooking,
                    modCookableComponent.CookingMinutes,
                    modCookableComponent.CookingUnitsRequired,
                    modCookableComponent.CookingWaterRequired,
                    CookingResult = modCookableComponent.CookingResult != null ? modCookableComponent.CookingResult.name : null ?? "",
                    modCookableComponent.BurntMinutes,
                    Type = modCookableComponent.Type.ToString(),
                    CookingAudio = modCookableComponent.CookingAudio != null ? modCookableComponent.CookingAudio.name : null ?? "",
                    StartCookingAudio = modCookableComponent.StartCookingAudio != null ? modCookableComponent.StartCookingAudio.name : null ?? ""
                },
                ModCookingPotComponent modCookingPotComponent => new
                {
                    modCookingPotComponent.DisplayNameLocalizationId,
                    modCookingPotComponent.DescriptionLocalizatonId,
                    modCookingPotComponent.InventoryActionLocalizationId,
                    modCookingPotComponent.WeightKG,
                    modCookingPotComponent.DaysToDecay,
                    modCookingPotComponent.MaxHP,
                    InitialCondition = modCookingPotComponent.InitialCondition.ToString(),
                    InventoryCategory = modCookingPotComponent.InventoryCategory.ToString(),
                    PickUpAudio = modCookingPotComponent.PickUpAudio != null ? modCookingPotComponent.PickUpAudio.name : "",
                    PutBackAudio = modCookingPotComponent.PutBackAudio != null ? modCookingPotComponent.PutBackAudio.name : "",
                    StowAudio = modCookingPotComponent.StowAudio != null ? modCookingPotComponent.StowAudio.name : "",
                    WornOutAudio = modCookingPotComponent.WornOutAudio != null ? modCookingPotComponent.WornOutAudio.name : "",
                    modCookingPotComponent.InspectOnPickup,
                    modCookingPotComponent.InspectDistance,
                    InspectAngles = new float[] { modCookingPotComponent.InspectAngles.x, modCookingPotComponent.InspectAngles.y, modCookingPotComponent.InspectAngles.z },
                    InspectOffset = new float[] { modCookingPotComponent.InspectOffset.x, modCookingPotComponent.InspectOffset.y, modCookingPotComponent.InspectOffset.z },
                    InspectScale = new float[] { modCookingPotComponent.InspectScale.x, modCookingPotComponent.InspectScale.y, modCookingPotComponent.InspectScale.z },
                    NormalModel = modCookingPotComponent.NormalModel != null ? modCookingPotComponent.NormalModel.name : "",
                    InspectModel = modCookingPotComponent.InspectModel != null ? modCookingPotComponent.InspectModel.name : "",

                    modCookingPotComponent.CanCookLiquid,
                    modCookingPotComponent.CanCookGrub,
                    modCookingPotComponent.CanCookMeat,
                    modCookingPotComponent.Capacity,
                    Template = modCookingPotComponent.Template != null ? modCookingPotComponent.Template.name : null ?? ""
                },
                ModFirstAidComponent modFirstAidComponent => new
                {
                    modFirstAidComponent.DisplayNameLocalizationId,
                    modFirstAidComponent.DescriptionLocalizatonId,
                    modFirstAidComponent.InventoryActionLocalizationId,
                    modFirstAidComponent.WeightKG,
                    modFirstAidComponent.DaysToDecay,
                    modFirstAidComponent.MaxHP,
                    InitialCondition = modFirstAidComponent.InitialCondition.ToString(),
                    InventoryCategory = modFirstAidComponent.InventoryCategory.ToString(),
                    PickUpAudio = modFirstAidComponent.PickUpAudio != null ? modFirstAidComponent.PickUpAudio.name : "",
                    PutBackAudio = modFirstAidComponent.PutBackAudio != null ? modFirstAidComponent.PutBackAudio.name : "",
                    StowAudio = modFirstAidComponent.StowAudio != null ? modFirstAidComponent.StowAudio.name : "",
                    WornOutAudio = modFirstAidComponent.WornOutAudio != null ? modFirstAidComponent.WornOutAudio.name : "",
                    modFirstAidComponent.InspectOnPickup,
                    modFirstAidComponent.InspectDistance,
                    InspectAngles = new float[] { modFirstAidComponent.InspectAngles.x, modFirstAidComponent.InspectAngles.y, modFirstAidComponent.InspectAngles.z },
                    InspectOffset = new float[] { modFirstAidComponent.InspectOffset.x, modFirstAidComponent.InspectOffset.y, modFirstAidComponent.InspectOffset.z },
                    InspectScale = new float[] { modFirstAidComponent.InspectScale.x, modFirstAidComponent.InspectScale.y, modFirstAidComponent.InspectScale.z },
                    NormalModel = modFirstAidComponent.NormalModel != null ? modFirstAidComponent.NormalModel.name : "",
                    InspectModel = modFirstAidComponent.InspectModel != null ? modFirstAidComponent.InspectModel.name : "",

                    modFirstAidComponent.ProgressBarMessage,
                    modFirstAidComponent.RemedyText,
                    modFirstAidComponent.InstantHealing,
                    FirstAidType = modFirstAidComponent.FirstAidType.ToString(),
                    modFirstAidComponent.TimeToUseSeconds,
                    modFirstAidComponent.UnitsPerUse,
                    UseAudio = modFirstAidComponent.UseAudio != null ? modFirstAidComponent.UseAudio.name : null ?? ""
                },
                ModToolComponent modToolComponent => new
                {
                    modToolComponent.DisplayNameLocalizationId,
                    modToolComponent.DescriptionLocalizatonId,
                    modToolComponent.InventoryActionLocalizationId,
                    modToolComponent.WeightKG,
                    modToolComponent.DaysToDecay,
                    modToolComponent.MaxHP,
                    InitialCondition = modToolComponent.InitialCondition.ToString(),
                    InventoryCategory = modToolComponent.InventoryCategory.ToString(),
                    PickUpAudio = modToolComponent.PickUpAudio != null ? modToolComponent.PickUpAudio.name : "",
                    PutBackAudio = modToolComponent.PutBackAudio != null ? modToolComponent.PutBackAudio.name : "",
                    StowAudio = modToolComponent.StowAudio != null ? modToolComponent.StowAudio.name : "",
                    WornOutAudio = modToolComponent.WornOutAudio != null ? modToolComponent.WornOutAudio.name : "",
                    modToolComponent.InspectOnPickup,
                    modToolComponent.InspectDistance,
                    InspectAngles = new float[] { modToolComponent.InspectAngles.x, modToolComponent.InspectAngles.y, modToolComponent.InspectAngles.z },
                    InspectOffset = new float[] { modToolComponent.InspectOffset.x, modToolComponent.InspectOffset.y, modToolComponent.InspectOffset.z },
                    InspectScale = new float[] { modToolComponent.InspectScale.x, modToolComponent.InspectScale.y, modToolComponent.InspectScale.z },
                    NormalModel = modToolComponent.NormalModel != null ? modToolComponent.NormalModel.name : "",
                    InspectModel = modToolComponent.InspectModel != null ? modToolComponent.InspectModel.name : "",

                    EquippedModelPrefab = modToolComponent.EquippedModelPrefab != null ? modToolComponent.EquippedModelPrefab.name : "",
                    modToolComponent.ImplementationType,
                    modToolComponent.EquippingAudio,

                    ToolType = modToolComponent.ToolType.ToString(),
                    ToolKind = modToolComponent.ToolKind.ToString(),
                    modToolComponent.DegradeOnUse,
                    Usage = modToolComponent.Usage.ToString(),
                    modToolComponent.SkillBonus,
                    modToolComponent.CraftingTimeMultiplier,
                    modToolComponent.DegradePerHourCrafting,
                    modToolComponent.BreakDown,
                    modToolComponent.BreakDownTimeMultiplier,
                    modToolComponent.ForceLocks,
                    ForceLockAudio = modToolComponent.ForceLockAudio != null ? modToolComponent.ForceLockAudio.name : null ?? "",
                    modToolComponent.IceFishingHole,
                    modToolComponent.IceFishingHoleDegradeOnUse,
                    modToolComponent.IceFishingHoleMinutes,
                    IceFishingHoleAudio = modToolComponent.IceFishingHoleAudio != null ? modToolComponent.IceFishingHoleAudio.name : null ?? "",
                    modToolComponent.CarcassHarvesting,
                    modToolComponent.MinutesPerKgMeat,
                    modToolComponent.MinutesPerKgFrozenMeat,
                    modToolComponent.MinutesPerHide,
                    modToolComponent.MinutesPerGut,
                    modToolComponent.DegradePerHourHarvesting,
                    modToolComponent.StruggleBonus,
                    modToolComponent.DamageMultiplier,
                    modToolComponent.FleeChanceMultiplier,
                    modToolComponent.TapMultiplier,
                    modToolComponent.CanPuncture,
                    modToolComponent.BleedoutMultiplier
                },
                ModGenericEquippableComponent modGenericEquippableComponent => new
                {
                    modGenericEquippableComponent.DisplayNameLocalizationId,
                    modGenericEquippableComponent.DescriptionLocalizatonId,
                    modGenericEquippableComponent.InventoryActionLocalizationId,
                    modGenericEquippableComponent.WeightKG,
                    modGenericEquippableComponent.DaysToDecay,
                    modGenericEquippableComponent.MaxHP,
                    InitialCondition = modGenericEquippableComponent.InitialCondition.ToString(),
                    InventoryCategory = modGenericEquippableComponent.InventoryCategory.ToString(),
                    PickUpAudio = modGenericEquippableComponent.PickUpAudio != null ? modGenericEquippableComponent.PickUpAudio.name : "",
                    PutBackAudio = modGenericEquippableComponent.PutBackAudio != null ? modGenericEquippableComponent.PutBackAudio.name : "",
                    StowAudio = modGenericEquippableComponent.StowAudio != null ? modGenericEquippableComponent.StowAudio.name : "",
                    WornOutAudio = modGenericEquippableComponent.WornOutAudio != null ? modGenericEquippableComponent.WornOutAudio.name : "",
                    modGenericEquippableComponent.InspectOnPickup,
                    modGenericEquippableComponent.InspectDistance,
                    InspectAngles = new float[] { modGenericEquippableComponent.InspectAngles.x, modGenericEquippableComponent.InspectAngles.y, modGenericEquippableComponent.InspectAngles.z },
                    InspectOffset = new float[] { modGenericEquippableComponent.InspectOffset.x, modGenericEquippableComponent.InspectOffset.y, modGenericEquippableComponent.InspectOffset.z },
                    InspectScale = new float[] { modGenericEquippableComponent.InspectScale.x, modGenericEquippableComponent.InspectScale.y, modGenericEquippableComponent.InspectScale.z },
                    NormalModel = modGenericEquippableComponent.NormalModel != null ? modGenericEquippableComponent.NormalModel.name : "",
                    InspectModel = modGenericEquippableComponent.InspectModel != null ? modGenericEquippableComponent.InspectModel.name : "",

                    EquippedModelPrefab = modGenericEquippableComponent.EquippedModelPrefab != null ? modGenericEquippableComponent.EquippedModelPrefab.name : null ?? "",
                    modGenericEquippableComponent.ImplementationType,
                    EquippingAudio = modGenericEquippableComponent.EquippingAudio != null ? modGenericEquippableComponent.EquippingAudio.name : null ?? ""
                },
                ModLiquidComponent modLiquidComponent => new
                {
                    modLiquidComponent.DisplayNameLocalizationId,
                    modLiquidComponent.DescriptionLocalizatonId,
                    modLiquidComponent.InventoryActionLocalizationId,
                    modLiquidComponent.WeightKG,
                    modLiquidComponent.DaysToDecay,
                    modLiquidComponent.MaxHP,
                    InitialCondition = modLiquidComponent.InitialCondition.ToString(),
                    InventoryCategory = modLiquidComponent.InventoryCategory.ToString(),
                    PickUpAudio = modLiquidComponent.PickUpAudio != null ? modLiquidComponent.PickUpAudio.name : "",
                    PutBackAudio = modLiquidComponent.PutBackAudio != null ? modLiquidComponent.PutBackAudio.name : "",
                    StowAudio = modLiquidComponent.StowAudio != null ? modLiquidComponent.StowAudio.name : "",
                    WornOutAudio = modLiquidComponent.WornOutAudio != null ? modLiquidComponent.WornOutAudio.name : "",
                    modLiquidComponent.InspectOnPickup,
                    modLiquidComponent.InspectDistance,
                    InspectAngles = new float[] { modLiquidComponent.InspectAngles.x, modLiquidComponent.InspectAngles.y, modLiquidComponent.InspectAngles.z },
                    InspectOffset = new float[] { modLiquidComponent.InspectOffset.x, modLiquidComponent.InspectOffset.y, modLiquidComponent.InspectOffset.z },
                    InspectScale = new float[] { modLiquidComponent.InspectScale.x, modLiquidComponent.InspectScale.y, modLiquidComponent.InspectScale.z },
                    NormalModel = modLiquidComponent.NormalModel != null ? modLiquidComponent.NormalModel.name : "",
                    InspectModel = modLiquidComponent.InspectModel != null ? modLiquidComponent.InspectModel.name : "",

                    LiquidType = modLiquidComponent.LiquidType.ToString(),
                    modLiquidComponent.LiquidCapacityLiters,
                    modLiquidComponent.RandomizedQuantity,
                    modLiquidComponent.LiquidLiters
                },
                ModPowderComponent modPowderComponent => new
                {
                    modPowderComponent.DisplayNameLocalizationId,
                    modPowderComponent.DescriptionLocalizatonId,
                    modPowderComponent.InventoryActionLocalizationId,
                    modPowderComponent.WeightKG,
                    modPowderComponent.DaysToDecay,
                    modPowderComponent.MaxHP,
                    InitialCondition = modPowderComponent.InitialCondition.ToString(),
                    InventoryCategory = modPowderComponent.InventoryCategory.ToString(),
                    PickUpAudio = modPowderComponent.PickUpAudio != null ? modPowderComponent.PickUpAudio.name : "",
                    PutBackAudio = modPowderComponent.PutBackAudio != null ? modPowderComponent.PutBackAudio.name : "",
                    StowAudio = modPowderComponent.StowAudio != null ? modPowderComponent.StowAudio.name : "",
                    WornOutAudio = modPowderComponent.WornOutAudio != null ? modPowderComponent.WornOutAudio.name : "",
                    modPowderComponent.InspectOnPickup,
                    modPowderComponent.InspectDistance,
                    InspectAngles = new float[] { modPowderComponent.InspectAngles.x, modPowderComponent.InspectAngles.y, modPowderComponent.InspectAngles.z },
                    InspectOffset = new float[] { modPowderComponent.InspectOffset.x, modPowderComponent.InspectOffset.y, modPowderComponent.InspectOffset.z },
                    InspectScale = new float[] { modPowderComponent.InspectScale.x, modPowderComponent.InspectScale.y, modPowderComponent.InspectScale.z },
                    NormalModel = modPowderComponent.NormalModel != null ? modPowderComponent.NormalModel.name : "",
                    InspectModel = modPowderComponent.InspectModel != null ? modPowderComponent.InspectModel.name : "",

                    PowderType = modPowderComponent.PowderType.ToString(),
                    modPowderComponent.CapacityKG,
                    modPowderComponent.ChanceFull
                },
                ModPurificationComponent modPurificationComponent => new
                {
                    modPurificationComponent.DisplayNameLocalizationId,
                    modPurificationComponent.DescriptionLocalizatonId,
                    modPurificationComponent.InventoryActionLocalizationId,
                    modPurificationComponent.WeightKG,
                    modPurificationComponent.DaysToDecay,
                    modPurificationComponent.MaxHP,
                    InitialCondition = modPurificationComponent.InitialCondition.ToString(),
                    InventoryCategory = modPurificationComponent.InventoryCategory.ToString(),
                    PickUpAudio = modPurificationComponent.PickUpAudio != null ? modPurificationComponent.PickUpAudio.name : "",
                    PutBackAudio = modPurificationComponent.PutBackAudio != null ? modPurificationComponent.PutBackAudio.name : "",
                    StowAudio = modPurificationComponent.StowAudio != null ? modPurificationComponent.StowAudio.name : "",
                    WornOutAudio = modPurificationComponent.WornOutAudio != null ? modPurificationComponent.WornOutAudio.name : "",
                    modPurificationComponent.InspectOnPickup,
                    modPurificationComponent.InspectDistance,
                    InspectAngles = new float[] { modPurificationComponent.InspectAngles.x, modPurificationComponent.InspectAngles.y, modPurificationComponent.InspectAngles.z },
                    InspectOffset = new float[] { modPurificationComponent.InspectOffset.x, modPurificationComponent.InspectOffset.y, modPurificationComponent.InspectOffset.z },
                    InspectScale = new float[] { modPurificationComponent.InspectScale.x, modPurificationComponent.InspectScale.y, modPurificationComponent.InspectScale.z },
                    NormalModel = modPurificationComponent.NormalModel != null ? modPurificationComponent.NormalModel.name : "",
                    InspectModel = modPurificationComponent.InspectModel != null ? modPurificationComponent.InspectModel.name : "",

                    modPurificationComponent.LitersPurify,
                    modPurificationComponent.ProgressBarDurationSeconds,
                    modPurificationComponent.ProgressBarLocalizationID,
                    PurifyAudio = modPurificationComponent.PurifyAudio != null ? modPurificationComponent.PurifyAudio.name : null ?? ""
                },
                ModRandomItemComponent modRandomItemComponent => new
                {
                    modRandomItemComponent.DisplayNameLocalizationId,
                    modRandomItemComponent.DescriptionLocalizatonId,
                    modRandomItemComponent.InventoryActionLocalizationId,
                    modRandomItemComponent.WeightKG,
                    modRandomItemComponent.DaysToDecay,
                    modRandomItemComponent.MaxHP,
                    InitialCondition = modRandomItemComponent.InitialCondition.ToString(),
                    InventoryCategory = modRandomItemComponent.InventoryCategory.ToString(),
                    PickUpAudio = modRandomItemComponent.PickUpAudio != null ? modRandomItemComponent.PickUpAudio.name : "",
                    PutBackAudio = modRandomItemComponent.PutBackAudio != null ? modRandomItemComponent.PutBackAudio.name : "",
                    StowAudio = modRandomItemComponent.StowAudio != null ? modRandomItemComponent.StowAudio.name : "",
                    WornOutAudio = modRandomItemComponent.WornOutAudio != null ? modRandomItemComponent.WornOutAudio.name : "",
                    modRandomItemComponent.InspectOnPickup,
                    modRandomItemComponent.InspectDistance,
                    InspectAngles = new float[] { modRandomItemComponent.InspectAngles.x, modRandomItemComponent.InspectAngles.y, modRandomItemComponent.InspectAngles.z },
                    InspectOffset = new float[] { modRandomItemComponent.InspectOffset.x, modRandomItemComponent.InspectOffset.y, modRandomItemComponent.InspectOffset.z },
                    InspectScale = new float[] { modRandomItemComponent.InspectScale.x, modRandomItemComponent.InspectScale.y, modRandomItemComponent.InspectScale.z },
                    NormalModel = modRandomItemComponent.NormalModel != null ? modRandomItemComponent.NormalModel.name : "",
                    InspectModel = modRandomItemComponent.InspectModel != null ? modRandomItemComponent.InspectModel.name : "",

                    ItemNames = modRandomItemComponent.ItemNames?.Select(gear => gear.name).ToArray(),
                },
                ModRandomWeightedItemComponent modRandomWeightedItemComponent => new
                {
                    modRandomWeightedItemComponent.DisplayNameLocalizationId,
                    modRandomWeightedItemComponent.DescriptionLocalizatonId,
                    modRandomWeightedItemComponent.InventoryActionLocalizationId,
                    modRandomWeightedItemComponent.WeightKG,
                    modRandomWeightedItemComponent.DaysToDecay,
                    modRandomWeightedItemComponent.MaxHP,
                    InitialCondition = modRandomWeightedItemComponent.InitialCondition.ToString(),
                    InventoryCategory = modRandomWeightedItemComponent.InventoryCategory.ToString(),
                    PickUpAudio = modRandomWeightedItemComponent.PickUpAudio != null ? modRandomWeightedItemComponent.PickUpAudio.name : "",
                    PutBackAudio = modRandomWeightedItemComponent.PutBackAudio != null ? modRandomWeightedItemComponent.PutBackAudio.name : "",
                    StowAudio = modRandomWeightedItemComponent.StowAudio != null ? modRandomWeightedItemComponent.StowAudio.name : "",
                    WornOutAudio = modRandomWeightedItemComponent.WornOutAudio != null ? modRandomWeightedItemComponent.WornOutAudio.name : "",
                    modRandomWeightedItemComponent.InspectOnPickup,
                    modRandomWeightedItemComponent.InspectDistance,
                    InspectAngles = new float[] { modRandomWeightedItemComponent.InspectAngles.x, modRandomWeightedItemComponent.InspectAngles.y, modRandomWeightedItemComponent.InspectAngles.z },
                    InspectOffset = new float[] { modRandomWeightedItemComponent.InspectOffset.x, modRandomWeightedItemComponent.InspectOffset.y, modRandomWeightedItemComponent.InspectOffset.z },
                    InspectScale = new float[] { modRandomWeightedItemComponent.InspectScale.x, modRandomWeightedItemComponent.InspectScale.y, modRandomWeightedItemComponent.InspectScale.z },
                    NormalModel = modRandomWeightedItemComponent.NormalModel != null ? modRandomWeightedItemComponent.NormalModel.name : "",
                    InspectModel = modRandomWeightedItemComponent.InspectModel != null ? modRandomWeightedItemComponent.InspectModel.name : "",

                    ItemNames = modRandomWeightedItemComponent.ItemNames?.Select(gear => gear.name).ToArray(),
                    modRandomWeightedItemComponent.ItemWeights
                },
                ModResearchComponent modResearchComponent => new
                {
                    modResearchComponent.DisplayNameLocalizationId,
                    modResearchComponent.DescriptionLocalizatonId,
                    modResearchComponent.InventoryActionLocalizationId,
                    modResearchComponent.WeightKG,
                    modResearchComponent.DaysToDecay,
                    modResearchComponent.MaxHP,
                    InitialCondition = modResearchComponent.InitialCondition.ToString(),
                    InventoryCategory = modResearchComponent.InventoryCategory.ToString(),
                    PickUpAudio = modResearchComponent.PickUpAudio != null ? modResearchComponent.PickUpAudio.name : "",
                    PutBackAudio = modResearchComponent.PutBackAudio != null ? modResearchComponent.PutBackAudio.name : "",
                    StowAudio = modResearchComponent.StowAudio != null ? modResearchComponent.StowAudio.name : "",
                    WornOutAudio = modResearchComponent.WornOutAudio != null ? modResearchComponent.WornOutAudio.name : "",
                    modResearchComponent.InspectOnPickup,
                    modResearchComponent.InspectDistance,
                    InspectAngles = new float[] { modResearchComponent.InspectAngles.x, modResearchComponent.InspectAngles.y, modResearchComponent.InspectAngles.z },
                    InspectOffset = new float[] { modResearchComponent.InspectOffset.x, modResearchComponent.InspectOffset.y, modResearchComponent.InspectOffset.z },
                    InspectScale = new float[] { modResearchComponent.InspectScale.x, modResearchComponent.InspectScale.y, modResearchComponent.InspectScale.z },
                    NormalModel = modResearchComponent.NormalModel != null ? modResearchComponent.NormalModel.name : "",
                    InspectModel = modResearchComponent.InspectModel != null ? modResearchComponent.InspectModel.name : "",

                    SkillType = modResearchComponent.SkillType.ToString(),
                    modResearchComponent.TimeRequirementHours,
                    modResearchComponent.SkillPoints,
                    modResearchComponent.NoBenefitAtSkillLevel,
                    ReadAudio = modResearchComponent.ReadAudio != null ? modResearchComponent.ReadAudio.name : null ?? ""
                },
                ModGenericComponent modGenericComponent => new
                {
                    modGenericComponent.DisplayNameLocalizationId,
                    modGenericComponent.DescriptionLocalizatonId,
                    modGenericComponent.InventoryActionLocalizationId,
                    modGenericComponent.WeightKG,
                    modGenericComponent.DaysToDecay,
                    modGenericComponent.MaxHP,
                    InitialCondition = modGenericComponent.InitialCondition.ToString(),
                    InventoryCategory = modGenericComponent.InventoryCategory.ToString(),
                    PickUpAudio = modGenericComponent.PickUpAudio != null ? modGenericComponent.PickUpAudio.name : "",
                    PutBackAudio = modGenericComponent.PutBackAudio != null ? modGenericComponent.PutBackAudio.name : "",
                    StowAudio = modGenericComponent.StowAudio != null ? modGenericComponent.StowAudio.name : "",
                    WornOutAudio = modGenericComponent.WornOutAudio != null ? modGenericComponent.WornOutAudio.name : "",
                    modGenericComponent.InspectOnPickup,
                    modGenericComponent.InspectDistance,
                    InspectAngles = new float[] { modGenericComponent.InspectAngles.x, modGenericComponent.InspectAngles.y, modGenericComponent.InspectAngles.z },
                    InspectOffset = new float[] { modGenericComponent.InspectOffset.x, modGenericComponent.InspectOffset.y, modGenericComponent.InspectOffset.z },
                    InspectScale = new float[] { modGenericComponent.InspectScale.x, modGenericComponent.InspectScale.y, modGenericComponent.InspectScale.z },
                    NormalModel = modGenericComponent.NormalModel != null ? modGenericComponent.NormalModel.name : "",
                    InspectModel = modGenericComponent.InspectModel != null ? modGenericComponent.InspectModel.name : ""
                },
                ModAccelerantBehaviour modAccelerantBehaviour => new
                {
                    modAccelerantBehaviour.DestroyedOnUse,
                    modAccelerantBehaviour.DurationOffset,
                    modAccelerantBehaviour.SuccessModifier
                },
                ModBurnableBehaviour modBurnableBehaviour => new
                {
                    modBurnableBehaviour.BurningMinutes,
                    modBurnableBehaviour.BurningMinutesBeforeAllowedToAdd,
                    modBurnableBehaviour.SuccessModifier,
                    modBurnableBehaviour.TempIncrease,
                    modBurnableBehaviour.DurationOffset
                },
                ModCarryingCapacityBehaviour modCarryingCapacityBehaviour => new
                {
                    modCarryingCapacityBehaviour.MaxCarryCapacityKGBuff
                },
                ModEvolveBehaviour modEvolveBehaviour => new
                {
                    TargetItemName = modEvolveBehaviour.TargetItemName != null ? modEvolveBehaviour.TargetItemName.name : null ?? "",
                    modEvolveBehaviour.EvolveHours,
                    modEvolveBehaviour.IndoorsOnly
                },
                ModFireStarterBehaviour modFireStarterBehaviour => new
                {
                    modFireStarterBehaviour.DestroyedOnUse,
                    modFireStarterBehaviour.NumberOfUses,
                    OnUseSoundEvent = modFireStarterBehaviour.OnUseSoundEvent != null ? modFireStarterBehaviour.OnUseSoundEvent.name : null ?? "",
                    modFireStarterBehaviour.RequiresSunLight,
                    modFireStarterBehaviour.RuinedAfterUse,
                    modFireStarterBehaviour.SecondsToIgniteTinder,
                    modFireStarterBehaviour.SecondsToIgniteTorch,
                    modFireStarterBehaviour.SuccessModifier
                },
                ModHarvestableBehaviour modHarvestableBehaviour => new
                {
                    Audio = modHarvestableBehaviour.Audio != null ? modHarvestableBehaviour.Audio.name : null ?? "",
                    modHarvestableBehaviour.Minutes,
                    YieldCounts = modHarvestableBehaviour.Yields?.Select(g => g.YieldCounts).ToArray(),
                    YieldNames = modHarvestableBehaviour.Yields?.Select(g => g.YieldNames.name).ToArray(),
                    RequiredToolNames = modHarvestableBehaviour.RequiredToolNames?.Select(tools => tools.name).ToArray(),
                },
                ModMillableBehaviour modMillableBehaviour => new
                {
                    modMillableBehaviour.RepairDurationMinutes,
                    RepairRequiredGear = modMillableBehaviour.RepairRequired?.Select(g => g.RepairRequiredGear.name).ToArray(),
                    RepairRequiredGearUnits = modMillableBehaviour.RepairRequired?.Select(g => g.RepairRequiredGearUnits).ToArray(),
                    modMillableBehaviour.CanRestoreFromWornOut,
                    modMillableBehaviour.RecoveryDurationMinutes,
                    RestoreRequiredGear = modMillableBehaviour.RestoreRequired?.Select(g => g.RestoreRequiredGear.name).ToArray(),
                    RestoreRequiredGearUnits = modMillableBehaviour.RestoreRequired?.Select(g => g.RestoreRequiredGearUnits).ToArray(),
                    Skill = modMillableBehaviour.Skill.ToString()
                },
                ModRepairableBehaviour modRepairableBehaviour => new
                {
                    Audio = modRepairableBehaviour.Audio != null ? modRepairableBehaviour.Audio.name : null ?? "",
                    modRepairableBehaviour.Minutes,
                    modRepairableBehaviour.Condition,
                    RequiredTools = modRepairableBehaviour.RequiredTools?.Select(requiredTools => requiredTools.name).ToArray(),
                    MaterialNames = modRepairableBehaviour.Materials?.Select(g => g.MaterialNames.name).ToArray(),
                    MaterialCounts = modRepairableBehaviour.Materials?.Select(g => g.MaterialCounts).ToArray(),
                },
                ModScentBehaviour modScentBehaviour => new
                {
                    ScentCategory = modScentBehaviour.ScentCategory.ToString()
                },
                ModSharpenableBehaviour modSharpenableBehaviour => new
                {
                    Audio = modSharpenableBehaviour.Audio != null ? modSharpenableBehaviour.Audio.name : null ?? "",
                    modSharpenableBehaviour.MinutesMin,
                    modSharpenableBehaviour.MinutesMax,
                    modSharpenableBehaviour.ConditionMin,
                    modSharpenableBehaviour.ConditionMax,
                    Tools = modSharpenableBehaviour.Tools?.Select(tools => tools.name).ToArray(),
                },
                ModStackableBehaviour modStackableBehaviour => new
                {
                    modStackableBehaviour.SingleUnitTextId,
                    modStackableBehaviour.MultipleUnitTextId,
                    modStackableBehaviour.StackSprite,
                    modStackableBehaviour.UnitsPerItem,
                    modStackableBehaviour.ChanceFull,
                    ShareStackWithGear = modStackableBehaviour.ShareStackWithGear?.Select(gearStack => gearStack.name).ToArray(),
                    InstantiateStackItem = modStackableBehaviour.InstantiateStackItem != null ? modStackableBehaviour.InstantiateStackItem.name : null ?? "",
                    modStackableBehaviour.StackConditionDifferenceConstraint
                },
                ModTinderBehaviour modTinderBehaviour => new
                {
                    modTinderBehaviour.DurationOffset,
                    modTinderBehaviour.SuccessModifier
                },
                _ => component
            };
        }
    }
}